FundamentosRails/Rails1/config/routes.rb
Rails.application.routes.draw do
  resources :direccions
  resources :mensajes
  resources :rols
  resources :usuarios
  resources :tweets
  resources :articulos
  resources :clientes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

FundamentosRails/Rails1/app/models/articulo.rb
class Articulo < ApplicationRecord
end

FundamentosRails/Rails1/app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  before_action :set_articulo, only: %i[ show edit update destroy ]

  # GET /articulos or /articulos.json
  def index
    @articulos = Articulo.all
  end

  # GET /articulos/1 or /articulos/1.json
  def show
  end

  # GET /articulos/new
  def new
    @articulo = Articulo.new
  end

  # GET /articulos/1/edit
  def edit
  end

  # POST /articulos or /articulos.json
  def create
    @articulo = Articulo.new(articulo_params)

    respond_to do |format|
      if @articulo.save
        format.html { redirect_to @articulo, notice: "Articulo was successfully created." }
        format.json { render :show, status: :created, location: @articulo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articulos/1 or /articulos/1.json
  def update
    respond_to do |format|
      if @articulo.update(articulo_params)
        format.html { redirect_to @articulo, notice: "Articulo was successfully updated." }
        format.json { render :show, status: :ok, location: @articulo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articulos/1 or /articulos/1.json
  def destroy
    @articulo.destroy
    respond_to do |format|
      format.html { redirect_to articulos_url, notice: "Articulo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_articulo
      @articulo = Articulo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def articulo_params
      params.require(:articulo).permit(:nombre, :descripcion, :cantidad)
    end
end

FundamentosRails/Rails1/app/helpers/articulos_helper.rb
module ArticulosHelper
end

FundamentosRails/Rails1/app/views/articulos/_form.html.erb
<%= form_with(model: articulo) do |form| %>
  <% if articulo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(articulo.errors.count, "error") %> prohibited this articulo from being saved:</h2>

      <ul>
        <% articulo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="field">
    <%= form.label :cantidad %>
    <%= form.number_field :cantidad %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

FundamentosRails/Rails1/app/views/articulos/edit.html.erb
<h1>Editing Articulo</h1>

<%= render 'form', articulo: @articulo %>

<%= link_to 'Show', @articulo %> |
<%= link_to 'Back', articulos_path %>

FundamentosRails/Rails1/app/views/articulos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articulos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Cantidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articulos.each do |articulo| %>
      <tr>
        <td><%= articulo.nombre %></td>
        <td><%= articulo.descripcion %></td>
        <td><%= articulo.cantidad %></td>
        <td><%= link_to 'Show', articulo %></td>
        <td><%= link_to 'Edit', edit_articulo_path(articulo) %></td>
        <td><%= link_to 'Destroy', articulo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Articulo', new_articulo_path %>

FundamentosRails/Rails1/app/views/articulos/new.html.erb
<h1>New Articulo</h1>

<%= render 'form', articulo: @articulo %>

<%= link_to 'Back', articulos_path %>

FundamentosRails/Rails1/app/views/articulos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @articulo.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @articulo.descripcion %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @articulo.cantidad %>
</p>

<%= link_to 'Edit', edit_articulo_path(@articulo) %> |
<%= link_to 'Back', articulos_path %>