FundamentosRails/Rails1/config/routes.rb
Rails.application.routes.draw do
  resources :direccions
  resources :mensajes
  resources :rols
  resources :usuarios
  resources :tweets
  resources :articulos
  resources :clientes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

FundamentosRails/Rails1/app/models/usuario.rb
class Usuario < ApplicationRecord
  belongs_to :rol
end

FundamentosRails/Rails1/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: %i[ show edit update destroy ]

  # GET /usuarios or /usuarios.json
  def index
    @usuarios = Usuario.all
    @rols = Rol.all
  end

  # GET /usuarios/1 or /usuarios/1.json
  def show
    @rols = Rol.all
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
    @rols = Rol.all
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios or /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: "Usuario was successfully created." }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1 or /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: "Usuario was successfully updated." }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1 or /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: "Usuario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:nombre, :apellido, :edad, :email, :contrasena, :rol_id)
    end
end

FundamentosRails/Rails1/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

FundamentosRails/Rails1/app/views/usuarios/_form.html.erb
<%= form_with(model: usuario) do |form| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
        <% usuario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :apellido %>
    <%= form.text_field :apellido %>
  </div>

  <div class="field">
    <%= form.label :edad %>
    <%= form.number_field :edad %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :contrasena %>
    <%= form.text_field :contrasena %>
  </div>

  <div class="field">
    <%= form.label :rol_id %>
    <%= collection_select(:usuario, :rol_id, Rol.all, :id, :nombre, prompt: true) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

FundamentosRails/Rails1/app/views/usuarios/edit.html.erb
<h1>Editar Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Mostrar', @usuario %> |
<%= link_to 'Atrás', usuarios_path %>

FundamentosRails/Rails1/app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Edad</th>
      <th>Email</th>
      <th>Rol</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.apellido %></td>
        <td><%= usuario.edad %></td>
        <td><%= usuario.email %></td>
        <td>
          <% @rols.each do |rol| %>
            <% if rol.id == usuario.rol_id %>
              <%= rol.nombre %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Mostrar', usuario %></td>
        <td><%= link_to 'Editar', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Eliminar', usuario, method: :delete, data: { confirm: '¿Está seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Usuario', new_usuario_path %>

<h1>Roles</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @rols.each do |rol| %>
      <tr>
        <td><%= rol.nombre %></td>
        <td><%= link_to 'Mostrar', rol %></td>
        <td><%= link_to 'Editar', edit_rol_path(rol) %></td>
        <td><%= link_to 'Eliminar', rol, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

FundamentosRails/Rails1/app/views/usuarios/new.html.erb
<h1>Nuevo Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Atrás', usuarios_path %>

FundamentosRails/Rails1/app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @usuario.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @usuario.apellido %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @usuario.edad %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>



<p>
  <strong>Rol:</strong>
  <% @rols.each do |rol| %>
    <% if rol.id == @usuario.rol_id %>
      <%= rol.nombre %>
    <% end %>
  <% end %>

</p>

<%= link_to 'Editar', edit_usuario_path(@usuario) %> |
<%= link_to 'Atrás', usuarios_path %>