FundamentosRails/Rails1/config/routes.rb
Rails.application.routes.draw do
  resources :direccions
  resources :mensajes
  resources :rols
  resources :usuarios
  resources :tweets
  resources :articulos
  resources :clientes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

FundamentosRails/Rails1/app/models/direccion.rb
class Direccion < ApplicationRecord
  belongs_to :usuario
end

FundamentosRails/Rails1/app/controllers/direccions_controller.rb
class DireccionsController < ApplicationController
  before_action :set_direccion, only: %i[ show edit update destroy ]

  # GET /direccions or /direccions.json
  def index
    @direccions = Direccion.all
  end

  # GET /direccions/1 or /direccions/1.json
  def show
  end

  # GET /direccions/new
  def new
    @direccion = Direccion.new
  end

  # GET /direccions/1/edit
  def edit
  end

  # POST /direccions or /direccions.json
  def create
    @direccion = Direccion.new(direccion_params)

    respond_to do |format|
      if @direccion.save
        format.html { redirect_to @direccion, notice: "Direccion was successfully created." }
        format.json { render :show, status: :created, location: @direccion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @direccion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /direccions/1 or /direccions/1.json
  def update
    respond_to do |format|
      if @direccion.update(direccion_params)
        format.html { redirect_to @direccion, notice: "Direccion was successfully updated." }
        format.json { render :show, status: :ok, location: @direccion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @direccion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /direccions/1 or /direccions/1.json
  def destroy
    @direccion.destroy
    respond_to do |format|
      format.html { redirect_to direccions_url, notice: "Direccion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_direccion
      @direccion = Direccion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def direccion_params
      params.require(:direccion).permit(:calle, :ciudad, :estado, :usuario_id)
    end
end

FundamentosRails/Rails1/app/helpers/direccions_helper.rb
module DireccionsHelper
end

FundamentosRails/Rails1/app/views/direccions/_form.html.erb
<%= form_with(model: direccion) do |form| %>
  <% if direccion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(direccion.errors.count, "error") %> prohibited this direccion from being saved:</h2>

      <ul>
        <% direccion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :calle %>
    <%= form.text_field :calle %>
  </div>

  <div class="field">
    <%= form.label :ciudad %>
    <%= form.text_field :ciudad %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.text_field :estado %>
  </div>

  <div class="field">
    <%= form.label :usuario_id %>
    <%= form.text_field :usuario_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

FundamentosRails/Rails1/app/views/direccions/edit.html.erb
<h1>Editando Dirección</h1>

<%= render 'form', direccion: @direccion %>

<%= link_to 'Mostrar', @direccion %> |
<%= link_to 'Atrás', direccions_path %>

FundamentosRails/Rails1/app/views/direccions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Direcciones</h1>

<table>
  <thead>
    <tr>
      <th>Calle</th>
      <th>Ciudad</th>
      <th>Estado</th>
      <th>Usuario</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @direccions.each do |direccion| %>
      <tr>
        <td><%= direccion.calle %></td>
        <td><%= direccion.ciudad %></td>
        <td><%= direccion.estado %></td>
        <td><%= direccion.usuario_id %></td>
        <td><%= link_to 'Mostrar', direccion %></td>
        <td><%= link_to 'Editar', edit_direccion_path(direccion) %></td>
        <td><%= link_to 'Eliminar', direccion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Dirección', new_direccion_path %>

FundamentosRails/Rails1/app/views/direccions/new.html.erb
<h1>Nueva Dirección</h1>

<%= render 'form', direccion: @direccion %>

<%= link_to 'Atrás', direccions_path %>

FundamentosRails/Rails1/app/views/direccions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Calle:</strong>
  <%= @direccion.calle %>
</p>

<p>
  <strong>Ciudad:</strong>
  <%= @direccion.ciudad %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @direccion.estado %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @direccion.usuario_id %>
</p>

<%= link_to 'Editar', edit_direccion_path(@direccion) %> |
<%= link_to 'Atrás', direccions_path %>